name: protscout-dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.24.0
  - pandas>=2.0.0
  - pytorch>=2.0.0
  - biopython>=1.81
  # Development dependencies
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.3.0
  - isort>=5.12.0
  - mypy>=1.4.0
  - pre-commit>=3.3.3
  - pip>=22.0.0
  - pip:
    - poetry>=1.5.0
    - ruff>=0.0.275
    - ipykernel