# ProtScout Workflow Configuration

condition: test
workdir: /home/ubuntu/lab4/ProtScout
modeldir: /home/ubuntu/lab4/model_weights
python_executable: /home/ubuntu/.conda/envs/protscout/bin/python
substrate_id: "PET"

paths:
  # Base directories
  input_base: /home/ubuntu/lab4/ProtScout/tests/data
  substrate_analogs: /home/ubuntu/lab4/ProtScout/tests/data/substrate_analogs.tsv
  artifacts_base: /home/ubuntu/lab4/ProtScout/tests/artifacts
  results_base: /home/ubuntu/lab4/ProtScout/tests/results
  # Optional model weight overrides
  geopoc_model: /home/ubuntu/lab4/model_weights/geopoc
  gatsol_model: /home/ubuntu/lab4/model_weights/gatsol
  # Override default log directory
  log_dir: /home/ubuntu/lab4/ProtScout/tests/logs
  
# Resource allocation
memory: 100g
workers: 2
quiet: false
max_retries: 2
preserve_artifacts: false  # set true to keep previous artifacts between runs

# Container configuration
containers:
  esmfold:
    image: ghcr.io/robaina/protscout-tools-esmfold:latest
    max_containers: 1
    
  esm2:
    image: ghcr.io/robaina/protscout-tools-esm2:latest
    max_containers: 1
    toks_per_batch: 4096
    model: esm2_t36_3B_UR50D
    include: per_tok
    
  catpred:
    image: ghcr.io/robaina/protscout-tools-catpred:latest
    
  temberture:
    image: ghcr.io/robaina/protscout-tools-temberture:latest
    
  geopoc:
    image: ghcr.io/robaina/protscout-tools-geopoc:latest
    tasks: "temp,pH,salt"
    
  gatsol:
    image: ghcr.io/robaina/protscout-tools-gatsol:latest
    batch_size: 32
    feature_batch: 4
    timeout: 600

# GPU and shared memory settings
resources:
  gpus: all
  shm_size: 100g

# Clean sequences configuration
clean_sequences:
  remove_duplicates: true
  prefix: ""

# Steps to execute (comment out to skip)
steps:
  - clean_sequences
  - esmfold
  - esm2
  - remove_sequences_without_pdb
  - prepare_catpred
  - catpred
  - temberture
  - geopoc
  - gatsol
  - classical_properties
  - process_temberture
  - process_geopoc
  - process_gatsol
  - process_catpred
  - consolidate_results