# ProtScout Workflow Configuration
# Condition: ultra

condition: ultra
workdir: /home/ubuntu/lab4/mangrove-plastic-degrading
modeldir: /home/ubuntu/lab4/model_weights
python_executable: /home/ubuntu/.conda/envs/protscout/bin/python

paths:
  # Override input/output base directories
  input_base: /custom/path/to/input/data
  output_base: /custom/path/to/results
  
  # Override specific paths
  substrate_analogs: /custom/path/to/substrate_analogs.tsv
  input_fasta: /custom/path/to/fasta/files
  
  # Override specific output directories
  structures: /custom/path/to/structures
  embeddings: /custom/path/to/embeddings

# Resource allocation
memory: 100g
workers: 2
quiet: true
max_retries: 2

# Container configuration
containers:
  esmfold:
    image: ghcr.io/new-atlantis-labs/esmfold:latest
    max_containers: 1
  
  esm2:
    image: ghcr.io/new-atlantis-labs/esm2:latest
    max_containers: 1
    toks_per_batch: 4096
  
  catpred:
    image: ghcr.io/new-atlantis-labs/catpred:latest
  
  temberture:
    image: ghcr.io/new-atlantis-labs/temberture:latest
  
  geopoc:
    image: ghcr.io/new-atlantis-labs/geopoc:latest
  
  gatsol:
    image: ghcr.io/new-atlantis-labs/gatsol:latest

# GPU and shared memory settings
resources:
  gpus: all
  shm_size: 100g

# Steps to execute (comment out to skip)
steps:
  - clean_sequences
  - esmfold
  - esm2
  - remove_sequences_without_pdb
  - prepare_catpred
  - catpred
  - temberture
  - geopoc
  - gatsol
  - classical_properties
  - process_temberture
  - process_geopoc
  - process_gatsol
  - process_catpred
  - consolidate_results